version: '3.5'
services:
  dify2openai:
    container_name: dify2openai
    image: baibaomen/dify2openai:latest
    network_mode: bridge
    ports:
      - "8083:3000"
    restart: always
    environment: 
      - DIFY_API_URL=http://192 168.13.241/v1
      - BOT_TYPE=Chat